spring.application.name=literalura

# Configuración de conexión a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=postgres
spring.datasource.password=TU_CONTRASENA_AQUI
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para crear/actualizar las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true